### ISSUE TITLE
integration

### ISSUE THREAD

**Issue by jaume-garcia** [EIA-Master/Project_2021_II#9]

**Comment by jaume-garcia** [comment]
Crec que hi ha una errata al programa integration.f90, quan es criden les boundary conditions pbc1 diria que falta passar-li també com a argument la L de la caixa, algú pot revisar-ho i confirmar-ho ?

**Comment by ignasipuch** [comment]
Jo també diria que falta la mida de la capsa de la simulació.

**Comment by ignasipuch** [comment]
Tanco l'issue perquè ja hem solucionat el problema! Bona feina
